### PR TITLE
add offset and limit to get_job_logs

### PR DESCRIPTION
**Pull request by Tianhao-Gu**
add offset and limit to `get_job_logs`

https://github.com/kbase/execution_engine2/issues/108

### CODE REVIEW

**Comment by Tianhao-Gu** [comment]
@bio-boris Do you mind taking a look?

**Comment by bio-boris** [comment]
Looks good. We could probably use a test for throwing an exception for providing skip lines and offset at the same time.

**Comment by bio-boris** [comment]
At some point we should probably slice up the array in mongo and not send the whole thing back and make the whole thing sit in memory.

**Comment by Tianhao-Gu** [comment]
@bio-boris Thanks. Added test for an exception.

**Pull request merged**
