### PR TITLE
DATAUP-424 remove slack calls

### PR DESCRIPTION
**Pull request by bio-boris**
# Description of PR purpose/changes

* Removes messages/dependency on slack for run_job
* We could put it back in for run_job, but not for run_job_batch, but if we do, we should wrap in try/catch and also launch a thread or process and not wait for it, and not be blocked by it

### CODE REVIEW

**Comment by bio-boris** [comment]
tagging @kbase/du_devs in the reviewers randomly chooses 3 reviewers, pretty neat

**Comment by MrCreosote** [comment]
Looks like tests are failing

**Review by MrCreosote — CHANGES_REQUESTED** [review]
Changes look fine, but I'm guessing that EE2RunJob_test.py needs to be altered, as it checks for calls to slack as part of the test

**Comment by MrCreosote** [comment]
IIRC there's 2 slack calls - one for create and one for update

**Comment by bio-boris** [comment]
> IIRC there's 2 slack calls - one for create and one for update

Hmm I'm not seeing it... Am I missing something?

**Comment by MrCreosote** [comment]
Never mind, I was thinking of kafka. Sorry

**Review by MrCreosote — APPROVED** [review]
LGTM

**Pull request merged**
